# Generated by Django 4.1.7 on 2023-02-22 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diag_id', models.AutoField(primary_key=True, serialize=False)),
                ('diag_date', models.DateField(auto_now_add=True)),
                ('diag_image', models.ImageField(blank=True, null=True, upload_to='diagnosis/images/')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
